# Site wide configuration

title: tonic
locale: en_US
description: Important papers in pediatrics.
logo: #site-logo.png
textlogo: #tonic
search: true
baseurl: /tonic
url: //jonjlee.github.io/tonic

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Enable disqus for all posts
comments: true

# Site owner
owner:
  name: Jonathan Lee
  avatar: http://www.gravatar.com/avatar/15f1403c873816140422561422556855.png
  email: jonjlee@gmail.com
  disqus-shortname: tonic-blog
  twitter: jonjlee
  facebook: #username
  github: jonjlee
  stackexchange: #http://stackoverflow.com/users/123456/username
  doximity: profile/6402118
  linkedin: jonjlee
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
